CREATE TABLE dbo.ChiTietTinNhan
(
	Ma INT IDENTITY(1,1) NOT NULL,
	NoiDung NVARCHAR(MAX) NOT NULL,
	ThoiDiemGui DATETIME DEFAULT GETDATE(),
	MaTinNhan INT NOT NULL,
	MaNguoiGui INT NOT NULL,
	DaDoc BIT DEFAULT 0
)