use rtcmfraf_Moodle;

GO
--Tạo cột điểm
CREATE TABLE dbo.CotDiem (
	Ma INT PRIMARY KEY IDENTITY(1, 1),
	MaKhoaHoc INT NOT NULL,
	Ten NVARCHAR(MAX) NOT NULL,
	MoTa NVARCHAR(MAX),
	HeSo INT NOT NULL DEFAULT 1,
	ThoiDiem DATETIME NOT NULL DEFAULT GETDATE(),
)