use rtcmfraf_Moodle;

GO
--Tạo khóa học
CREATE TABLE dbo.KhoaHoc(
	Ma INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	Ten NVARCHAR(MAX) NOT NULL,
	MoTa NVARCHAR(MAX) NOT NULL,
	MaHinhDaiDien INT DEFAULT NULL,
	MaChuDe INT NOT NULL,
	MaNguoiTao INT NOT NULL,
	ThoiDiemTao DATETIME DEFAULT GETDATE() NOT NULL,
	Han DATETIME DEFAULT NULL,
	CanDangKy BIT DEFAULT NULL,
	HanDangKy DATETIME DEFAULT NULL,
	PhiThamGia INT DEFAULT NULL,
	CheDoRiengTu NVARCHAR(MAX) NOT NULL,
	CoBangDiem BIT DEFAULT NULL,
	CoBangDiemDanh BIT DEFAULT NULL,
	CanDuyetBaiViet BIT DEFAULT NULL
)